AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - Gemfile

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/Documentation:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
