AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  DisplayCopNames: true
  SuggestExtensions: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
